import Link from "next/link";
import { ArrowRight, BookOpenText, Check, ChevronRight, Coffee, MessageCircle, Mic, PenLine, Sparkles, UsersRound } from "lucide-react";

const offerings = [
  { number: "01", icon: UsersRound, title: "Group classes", eyebrow: "Intermediate · Advanced", hook: "A place to speak, think and hold your own in Spanish.", body: "Small, live groups where you use Spanish for real: talk, debate, ask questions and build confidence alongside learners at your level.", details: ["Live online sessions in small groups", "Intermediate and advanced levels", "Real conversation with guidance and feedback"], color: "var(--purple-light)", accent: "var(--purple-dark)" },
  { number: "02", icon: Coffee, title: "Your Practice Partner", eyebrow: "Coffee · Walks · Buenos Aires", hook: "Spanish doesn't have to happen in a classroom.", body: "Book a couple of hours with Victoria outside the lesson: a coffee, a walk, or a plan that gets you off-screen. No syllabus, no pressure—just real conversation at your pace.", details: ["In-person sessions in Buenos Aires", "Coffee, walks or an activity you choose together", "Use Spanish in real-life situations"], color: "var(--mint-light)", accent: "var(--mint-darkest)" },
  { number: "03", icon: Mic, title: "Voice Note Coaching", eyebrow: "WhatsApp · Throughout your week", hook: "Practise on your own time. Get human feedback.", body: "Send Victoria a voice note whenever Spanish comes up in your week. She'll reply with feedback on pronunciation, rhythm and vocabulary, plus a model recording to repeat after.", details: ["Personal feedback on WhatsApp", "Pronunciation, accent and expression", "A weekly recap of your learning patterns"], color: "var(--blush)", accent: "var(--blush-dark)" },
  { number: "04", icon: BookOpenText, title: "Grammar workshops", eyebrow: "Subjunctive · Past simple", hook: "The two topics everyone asks for, explained to be used.", body: "Short videos and hands-on practice to understand the logic behind the tenses. Less memorising lists, more real examples until using them feels natural.", details: ["Focused, accessible workshops", "Subjunctive and past simple", "Everyday examples, not isolated drills"], color: "var(--cream)", accent: "var(--navy)" },
];

export default function HomePage() {
  return <main className="min-h-screen bg-[#fffdfb] text-[var(--navy)]"><Nav /><Hero /><Offerings /><Writing /><Sobremesa /><HowItWorks /><Closing /><Footer /></main>;
}

function Nav() {
  return <nav className="sticky top-0 z-50 flex h-16 items-center justify-between border-b border-[rgba(71,67,80,0.1)] bg-[#fffdfb]/95 px-5 backdrop-blur md:px-10">
    <Link href="/" className="text-lg font-extrabold tracking-[-0.04em] text-[var(--navy)]">el<span className="text-[var(--purple-dark)]">Sur</span><span className="ml-2 text-xs font-semibold tracking-normal text-[var(--navy-light)]">with Victoria</span></Link>
    <div className="flex items-center gap-4"><a href="#sessions" className="hidden text-sm font-semibold text-[var(--navy-light)] transition hover:text-[var(--purple-dark)] sm:block">Offerings</a><Link href="/login" className="hidden text-sm font-semibold text-[var(--navy-light)] transition hover:text-[var(--purple-dark)] md:block">Sign in</Link><a href="#contact" className="rounded-full bg-[var(--purple-dark)] px-4 py-2 text-sm font-bold text-white transition hover:bg-[var(--purple-darkest)]">Ask about availability</a></div>
  </nav>;
}

function Hero() {
  return <section className="relative overflow-hidden px-5 pb-20 pt-16 md:px-10 md:pb-28 md:pt-24">
    <div className="absolute -right-24 -top-32 size-[28rem] rounded-full bg-[var(--purple-light)] opacity-70 blur-3xl" /><div className="absolute -bottom-40 -left-32 size-[26rem] rounded-full bg-[var(--mint-light)] opacity-80 blur-3xl" />
    <div className="relative mx-auto max-w-6xl"><div className="grid items-end gap-12 lg:grid-cols-[1.25fr_0.75fr]"><div>
      <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[rgba(122,79,196,0.16)] bg-white px-3.5 py-1.5 text-xs font-bold uppercase tracking-[0.12em] text-[var(--purple-dark)]"><Sparkles className="size-3.5" aria-hidden /> Argentine Spanish, with Victoria</div>
      <h1 className="max-w-3xl text-5xl font-black leading-[0.98] tracking-[-0.06em] text-[var(--navy)] md:text-7xl">Make Spanish part of your life.</h1>
      <p className="mt-7 max-w-xl text-lg leading-relaxed text-[var(--navy-light)] md:text-xl">Classes, practice and workshops for learners who already have something to say—and want to say it with more ease, precision and their own voice.</p>
      <div className="mt-9 flex flex-wrap gap-3"><a href="#sessions" className="inline-flex items-center gap-2 rounded-full bg-[var(--purple-dark)] px-6 py-3.5 text-sm font-bold text-white transition hover:bg-[var(--purple-darkest)]">Explore the offerings <ArrowRight className="size-4" aria-hidden /></a><a href="#contact" className="rounded-full border border-[rgba(71,67,80,0.18)] bg-white px-6 py-3.5 text-sm font-bold text-[var(--navy)] transition hover:border-[var(--purple)]">Find my format</a></div>
    </div><div className="rounded-[2rem] border border-white/80 bg-white/80 p-7 shadow-[0_18px_70px_rgba(61,37,112,0.12)] backdrop-blur md:p-8"><div className="text-sm font-bold text-[var(--purple-dark)]">This isn't an app that corrects you.</div><p className="mt-3 text-2xl font-extrabold leading-tight tracking-[-0.04em] text-[var(--navy)]">It's a teacher who knows your voice, listens closely and nudges you a little further.</p><div className="mt-7 border-t border-[rgba(71,67,80,0.1)] pt-5 text-sm leading-relaxed text-[var(--navy-light)]">Online from anywhere, in person in Buenos Aires, and on WhatsApp throughout your week.</div></div></div></div>
  </section>;
}

function Offerings() {
  return <section id="sessions" className="bg-white px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[var(--mint-darkest)]">Four ways to learn</p><h2 className="mt-3 text-4xl font-black tracking-[-0.055em] text-[var(--navy)] md:text-5xl">Choose how you want Spanish to show up in your life.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-2">
    {offerings.map(({ number, icon: Icon, title, eyebrow, hook, body, details, color, accent }) => <article key={title} className="group rounded-[1.75rem] border border-[rgba(71,67,80,0.08)] p-7 md:p-8" style={{ background: color }}><div className="flex items-start justify-between gap-4"><div className="flex size-11 items-center justify-center rounded-2xl bg-white shadow-sm" style={{ color: accent }}><Icon className="size-5" aria-hidden /></div><span className="text-xs font-black tracking-[0.16em]" style={{ color: accent }}>{number}</span></div><p className="mt-8 text-xs font-bold uppercase tracking-[0.13em]" style={{ color: accent }}>{eyebrow}</p><h3 className="mt-2 text-3xl font-black tracking-[-0.045em] text-[var(--navy)]">{title}</h3><p className="mt-4 text-lg font-bold leading-snug text-[var(--navy)]">{hook}</p><p className="mt-4 text-sm leading-relaxed text-[var(--navy-light)]">{body}</p><ul className="mt-6 space-y-2.5 border-t border-[rgba(71,67,80,0.1)] pt-5">{details.map((detail) => <li key={detail} className="flex gap-2.5 text-sm text-[var(--navy)]"><Check className="mt-0.5 size-4 shrink-0" style={{ color: accent }} aria-hidden />{detail}</li>)}</ul><a href="#contact" className="mt-7 inline-flex items-center gap-1 text-sm font-extrabold transition group-hover:gap-2" style={{ color: accent }}>Ask about this format <ChevronRight className="size-4" aria-hidden /></a></article>)}
  </div></div></section>;
}

function Writing() {
  return <section className="bg-[var(--navy)] px-5 py-20 text-white md:px-10 md:py-28"><div className="mx-auto grid max-w-6xl items-center gap-12 lg:grid-cols-[0.8fr_1.2fr]"><div><div className="flex size-12 items-center justify-center rounded-2xl bg-[var(--purple)] text-[var(--purple-darkest)]"><PenLine className="size-6" aria-hidden /></div><p className="mt-7 text-sm font-bold uppercase tracking-[0.16em] text-[var(--mint)]">Also: creative writing</p><h2 className="mt-3 text-4xl font-black leading-none tracking-[-0.055em] md:text-5xl">Write to say something, not just to conjugate.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-[1.5rem] bg-white/10 p-6 ring-1 ring-white/10"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--mint)]">Intermediate</p><h3 className="mt-3 text-2xl font-extrabold tracking-[-0.04em]">Find your voice.</h3><p className="mt-4 text-sm leading-relaxed text-white/70">Short pieces, guided prompts and thoughtful feedback to start writing freely in Spanish.</p></div><div className="rounded-[1.5rem] bg-[var(--purple-dark)] p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--mint)]">Advanced</p><h3 className="mt-3 text-2xl font-extrabold tracking-[-0.04em]">Write for readers.</h3><p className="mt-4 text-sm leading-relaxed text-white/80">Sessions with native Spanish speakers: longer pieces, real critique and a reading that goes beyond your errors.</p></div></div></div></section>;
}

function Sobremesa() {
  return <section className="bg-[var(--cream)] px-5 py-16 md:px-10"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 rounded-[1.75rem] border border-[rgba(71,67,80,0.1)] bg-white p-7 md:flex-row md:items-center md:p-9"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[0.15em] text-[var(--blush-dark)]">Special series</p><h2 className="mt-2 text-3xl font-black tracking-[-0.05em] text-[var(--navy)]">Sobremesa Sessions</h2><p className="mt-3 leading-relaxed text-[var(--navy-light)]">Literature, current affairs and debate in Spanish. For people who enjoy a conversation that lingers after the plates are cleared.</p></div><a href="#contact" className="shrink-0 rounded-full border border-[var(--blush-dark)] px-5 py-3 text-sm font-bold text-[var(--blush-dark)] transition hover:bg-[var(--blush)]">Keep me posted</a></div></section>;
}

function HowItWorks() {
  const steps = [["01", "Tell Victoria where you are", "Your level, your goals and how much room Spanish has in your week."], ["02", "Choose the format", "A group class, a workshop, in-person practice or WhatsApp voice notes."], ["03", "Start using it", "With a format that challenges you while fitting your real life."]];
  return <section className="bg-white px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[var(--purple-dark)]">Simple and personal</p><h2 className="mt-3 max-w-2xl text-4xl font-black tracking-[-0.055em] text-[var(--navy)] md:text-5xl">You don't need to fit into a generic course.</h2><div className="mt-12 grid gap-7 md:grid-cols-3">{steps.map(([number, title, description]) => <div key={number} className="border-t-2 border-[var(--mint)] pt-5"><span className="text-sm font-black text-[var(--mint-darkest)]">{number}</span><h3 className="mt-4 text-xl font-extrabold tracking-[-0.03em] text-[var(--navy)]">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[var(--navy-light)]">{description}</p></div>)}</div></div></section>;
}

function Closing() {
  return <section id="contact" className="bg-[var(--purple-darkest)] px-5 py-20 text-center text-white md:px-10 md:py-28"><MessageCircle className="mx-auto size-7 text-[var(--mint)]" aria-hidden /><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-black leading-[1.02] tracking-[-0.055em] md:text-6xl">Let Spanish become something you use, not just something you study.</h2><p className="mx-auto mt-6 max-w-xl text-base leading-relaxed text-white/75">Create an account to hear about upcoming groups, workshops and available formats with Victoria.</p><Link href="/register" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[var(--mint)] px-6 py-3.5 text-sm font-extrabold text-[var(--mint-darkest)] transition hover:bg-white">Create an account to begin <ArrowRight className="size-4" aria-hidden /></Link><p className="mt-4 text-xs text-white/50">The family learning app remains available for existing members.</p></section>;
}

function Footer() {
  return <footer className="flex flex-col justify-between gap-4 bg-[var(--navy)] px-5 py-7 text-sm text-white/60 md:flex-row md:px-10"><p><span className="font-extrabold text-white">elSur</span> with Victoria</p><div className="flex gap-5"><Link href="/login" className="transition hover:text-white">Sign in</Link><Link href="/families" className="transition hover:text-white">Family learning app</Link></div></footer>;
}
